<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'user' => '用户',
    'username' => '用户名',
    'email' => '邮箱',
    'created_at' => '创建日期',
    'updated_at' => '更新日期',
    'status' => '状态',
    'Inactive' => '未激活',
    'Active' => '激活',
    '<b>{totalCount, number}</b> .'=>'共 <b>{totalCount, number}</b> 条数据.',
];
