<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'system' => '系统设置',
    'menu' => '菜单管理',
    'route' => '路由管理',
    'user' => '用户管理',
    'permission' => '权限管理',
    'role' => '角色管理',
    'user-index' => '用户列表',
    'user/index' => '用户列表',
    'user/update' => '用户编辑',
    'user/account/update' => '个人信息',
    'user/assignment/view' => '角色分配',
    'user/create' => '添加用户',

    'product' => '产品管理',
    'product/size' => '尺码管理',
    'product/size/update' => '尺码管理',
    'product/product/import-price' => '导入价格',
    'product/product/import-stocks' => '导入库存',
    'product/product/import-stocks-for-increment' => '累加库存',
    'product/product' => '产品列表',
    'product/product/index' => '产品列表',
    'product/product/create' => '添加产品',
    'product/product/update' => '更新产品',
    'product/product/update-attributes' => '更新产品属性',
    'product/product/view' => '产品详情',
    'template' => '版图管理',
    'product/template/index' => '版图管理',
    'product/template/create' => '开版',
    'product/template/update' => '开版',
    'product/template/view' => '查看版图',
    'product/template/studio-index' => '渲染列表',
    'product/template/factory-index' => '开版列表',
    'product/template/process-list' => '选品列表',
    'product/template/studio-price-list' => '渲染费用',
    'product/template/update-attributes' => '版图属性',

    'product/export/sku' => '导出产品',

    'order' => '订单管理',
    'order/order' => '订单管理',
    'order/order/index' => '订单列表',
    'order/order/confirm-list' => '变更确认',
    'order/order/change-confirm-list' => '订单变更确认',
    'order/order/create' => '创建订单',
    'order/order/import-shipments' => '导入物流',
    'order/import-shipments' => '导入物流',
    'order/order/view' => '订单详情',
    'order/order/view-history' => '订单历史详情',
    'order/order/distribution-view' => '配货订单详情',
    'order/order/create-confirm-list' => '订单审核',
    'order/issue/index' => '联系客户',
    'order/refund/index' => '退款管理',


    'website' => '网站管理',
    'website/index' => '网站管理',
    'website/create' => '新增网站',
    'website/update' => '编辑网站',

    'factory' => '工厂管理',
    'factory/custom' => '定制生产',
    'factory/custom/custom' => '定制生产',
    'factory/stockup' => '库存生产',
    'factory/stocks/stockup' => '库存生产',
    'stocks'=>'库存管理',
    'factory/stocks/stocks' => '工厂款',
    'factory/stocks/taobao' => '淘宝款',
    'factory/stocks/list' => '库存列表',
    'factory/stocks/stocks-list' => '库存列表',
    'factory/history/list' => '生产记录',
    'factory/report/index' => '生产报告',
    'factory/product/index' => '版号管理',
    'factory/confirm/index' => '变更确认',


    'distribution' => '配货管理',
    'distribution/custom' => '定制单配货',
    'distribution/custom/custom' => '定制单配货',
    'distribution/stock' => '库存单配货',
    'distribution/stock/stock' => '库存单配货',
    'distribution/taobao' => '淘宝单配货',
    'distribution/taobao/taobao' => '淘宝单配货',
    'distribution/mixture' => '混合单配货',

    'distribution/rejects/index' => '次品管理',

    'distribution/mixture/mixture' => '混合单配货',
    'dashboard/distribution/report' => '配货报告',
    'dashboard/order/index' => '我的订单',

    'comment/create'=>'添加备注',
    'category'=>'分类管理',
    'category/index'=>'分类管理',

    'shipment'=>'物流管理',
    'shipment/export/order-list'=>'物流订单',
    'shipment/fee/index'=>'物流费用',
    'shipment/fee/import'=>'导入物流费用',

    'cron/cron'=>'定时任务',
    'cron/cron/index'=>'定时任务',

    'system/config'=>'系统配置',
    'system/config/forecasting'=>'库存预测',
    'stocks/forecasting/index'=>'库存预测',
    'stocks/forecasting/sales-history'=>'产品销售历史',
    'system/ip/index'=>'访问限制',

    'sales'=>'营销管理',
    'sales/sales/report'=>'销售统计',
    'sales/order/index'=>'订单分析',
    'sales/product/index'=>'销售分析',
    'sales/product/top100'=>'销量排行榜',
    'sales/product/sales-history'=>'销售历史',
    
    'count'=>'统计管理',
    'count/order/index'=>'订单统计',
    'count/coupon/index'=>'Coupon统计',
    'count/top10/index'=>'Top10统计',
    'count/pct/index'=>'客单价统计',
    
    'loan'=>'财务管理',
    'finance/loan/index'=>'货贷统计',
    'finance/revenue/index'=>'营收统计',

    'dashboard'=>'个人中心',
    'dashboard/distribution/index'=>'我的工作',

    'service'=>'客服专栏',
    'service/service/issue-tags'=>'问题分类',
    'service/service/issue-list'=>'问题列表',
    'service/service/create-issue'=>'问题登记',
    'service/service/handle-issue'=>'跟踪问题',
    'service/service/view-issue'=>'问题详情',
    'service/service/solution-list'=>'客服指南',
    'service/service/solution-create'=>'新增客服指南',
    'service/service/solution-view'=>'客服指南详情',


    'supplies/material/index'=>'耗材管理',
    'supplies/material/create'=>'添加耗材',
    'supplies/material/update'=>'编辑耗材',
    'supplies/packing/index'=>'耗材进货',
    'supplies/packing/create'=>'进货',
    'supplies/packing/update'=>'进货修改',
];
