<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [

    '/admin/assignment/assign' => '系统设置',
    '/admin/default/index' => '首页',
    '/admin/user/index' => '路由管理',
    'user' => '用户管理',
    'permission' => '权限管理',
    'role' => '角色管理',
    'user-index' => '用户列表',
    '/*' => '全部权限',
    '/user/*' => '用户管理',
];
